### ISSUE TITLE
Firefox Compatibility

### ISSUE THREAD

**Issue by sexnine** [sexnine/cshs-website#3]
A few issues with Firefox compatibility.

## Underlines
| Chrome  | Firefox |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/25860388/159113713-fe592156-6054-4d46-aef9-95b5067e7268.png) | ![image](https://user-images.githubusercontent.com/25860388/159113727-32bd13e6-96f2-4919-ae6a-be61bee6312d.png)  |

## Blur
| Chrome | Firefox |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/25860388/159113791-799508d7-938d-497b-b4ae-6110b5d40336.png) | ![image](https://user-images.githubusercontent.com/25860388/159113801-ad54d82b-c729-4f60-aaf3-58316263036c.png) |

## To be fixed

- [x] Underlines
- [ ] Blur

**Comment by sexnine** [comment]
Underlines fixed in 834662d

**Comment by kufupa** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/77014615/161808767-40569237-7f88-4d48-a06f-40c5d828e030.png)

Firefox:
![image](https://user-images.githubusercontent.com/77014615/161808883-7d30070f-6728-415d-bb65-196b8fd9de56.png)

**Comment by sexnine** [comment]
It seems you cannot do a background blur in Firefox and so the only way of making a similar feeling is by setting a higher opacity.

This has been fixed in a3b7bef.

**Comment by sexnine** [comment]
> Chrome:
> ![image](https://user-images.githubusercontent.com/77014615/161808767-40569237-7f88-4d48-a06f-40c5d828e030.png)
> 
> Firefox:
> ![image](https://user-images.githubusercontent.com/77014615/161808883-7d30070f-6728-415d-bb65-196b8fd9de56.png)
> 

@MooMooMod Could you explain what you're trying to say here?  I don't understand..
