### ISSUE TITLE
Button press no box

### ISSUE THREAD

**Issue by kufupa** [sexnine/cshs-website#6]
![image](https://user-images.githubusercontent.com/77014615/161812238-22bdb646-c513-4e7f-9d92-558ac22414d8.png)

When pressing "Free domains", it begins to scroll you down but stops when it reaches the end of the website (obviously). It does not have a box around "Free domains" however.

Solution: Extend website with whitespace (temporary) or add a small footer at the end
![image](https://user-images.githubusercontent.com/77014615/161812485-9d5b96e8-3908-4d82-a552-72d5a2c0871a.png)
This is the apple one, obviously we havent got that much info but maybe some small text with the discord, reddit links? 

I'm sure the issue will be "fixed" automatically with more work being done on the website

**Comment by sexnine** [comment]
Works as intended.

Adding unnecessary whitespace to the bottom would not look nice, it would also not work for all screen sizes.

**Comment by sexnine** [comment]
I should also add if you look in the backend branch, the Navbar is being changed from scrolling to pages as there will be more pages than just the home page.
